const cats=['Home & Living','Electronics','Fashion','Beauty & Care','Sports & Outdoors','Kids & Toys'];
const positions=[6.73,23.8,41.1,58.4,76.5,93.3];
const products=[{id:1,name:'Wireless Headphones',category:'Electronics',price:49,x:7.05,y:96.2,desc:'A softer soundtrack for your day. A clean, over-ear silhouette in a warm neutral finish.',type:'product'}, {id:2,name:'Everyday Tote',category:'Fashion',price:24,x:31.8,y:96.2,desc:'Your daily carry, with a little Rosaino colour. A roomy tote featuring our signature flowing ribbon.',type:'product'}, {id:3,name:'Ceramic Table Lamp',category:'Home & Living',price:39,x:56.45,y:96.2,desc:'A warm corner starts here. A sculptural ceramic silhouette to bring a little calm to your space.',type:'product'}, {id:4,name:'Insulated Bottle',category:'Sports & Outdoors',price:22,x:81.05,y:96.2,desc:'A companion for your everyday adventures. Rosaino midnight, finished with our colourful ribbon icon.',type:'product'}, {id:5,name:'Daily Care Edit',category:'Beauty & Care',price:32,x:58.4,y:65.3,desc:'An introduction to everyday care, with a coordinated collection for your daily routine.',type:'category'}, {id:6,name:'Little Discoveries Set',category:'Kids & Toys',price:29,x:93.3,y:65.3,desc:'A playful collection of soft textures and colourful shapes for a world of little discoveries.',type:'category'}];
let category='All',query='',cart={};try{cart=JSON.parse(localStorage.getItem('rosaino-bag')||'{}');if(!cart||Array.isArray(cart)||typeof cart!=='object')cart={};for(const k of Object.keys(cart))if(!products.some(p=>String(p.id)===k)||!Number.isInteger(cart[k])||cart[k]<1||cart[k]>99)delete cart[k]}catch{cart={}}
const $=s=>document.querySelector(s),money=n=>'$'+n.toFixed(2),photo=p=>`background-position:${p.x}% ${p.y}%;${p.type==='category'?'background-size:714.42% auto;':''}`;
$('#year').textContent=new Date().getFullYear();
$('#nav').innerHTML=['Shop all',...cats].map((c,i)=>`<button data-category="${i?c:'All'}">${c}</button>`).join('');
$('#categories').innerHTML=cats.map((c,i)=>`<button class="category" data-category="${c}"><div class="category-photo" role="img" aria-label="${c} collection" style="background-position:${positions[i]}% 65.3%"></div><div class="category-label"><span>${c}</span><span aria-hidden="true">↗</span></div></button>`).join('');
function render(){const list=products.filter(p=>(category==='All'||p.category===category)&&(`${p.name} ${p.category}`.toLowerCase().includes(query)));$('#products').innerHTML=list.length?list.map(p=>`<article class="product"><div class="product-visual"><button class="product-open" data-detail="${p.id}" aria-label="View ${p.name}"><div class="product-photo" role="img" aria-label="${p.name}" style="${photo(p)}"></div></button><button class="add-button" data-add="${p.id}" aria-label="Add ${p.name} to bag">+</button></div><div class="product-meta"><div><button data-detail="${p.id}" style="padding:0;text-align:left"><h3>${p.name}</h3></button><p>${p.category}</p></div><span class="price">$${p.price}</span></div><div class="swatches" aria-hidden="true"><i></i><i></i><i></i></div></article>`).join(''):'<div class="empty">No discoveries found. Try a different search or explore all collections.</div>';$('#results').textContent=`${list.length} discoveries · USD`;$('#active-filter').textContent=category==='All'?'All collections':category;$('#product-title').textContent=query?'Your discoveries.':category==='All'?'Everyday favourites.':category+'.';document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.category===category);b.setAttribute('aria-pressed',String(b.dataset.category===category))})}
function filter(c){category=c;render();$('#shop').scrollIntoView({behavior:'smooth'})}
function save(){try{localStorage.setItem('rosaino-bag',JSON.stringify(cart))}catch{}$('#bag-count').textContent=Object.values(cart).reduce((a,b)=>a+b,0)}
let toastTimer;function add(id){cart[id]=Math.min((cart[id]||0)+1,99);save();$('#toast').textContent='Added to your bag';$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2200);if($('#bag').open)renderBag()}
function detail(id){const p=products.find(p=>p.id===id);$('#detail-content').innerHTML=`<div class="detail-grid"><div class="product-photo" role="img" aria-label="${p.name}" style="${photo(p)}"></div><div><span class="eyebrow">${p.category}</span><h2 id="detail-title">${p.name}</h2><p>${p.desc}</p><div class="detail-price">${money(p.price)} <small style="font-size:13px">USD</small></div><button class="primary" data-add="${p.id}">Add to bag <span>+</span></button><p class="detail-note">Preview collection. Product specifications, pricing and availability will be confirmed before launch.</p></div></div>`;$('#detail').showModal()}
function renderBag(){const list=products.filter(p=>cart[p.id]);$('#bag-items').innerHTML=list.length?list.map(p=>`<div class="bag-row"><div><h3>${p.name}</h3><small>${money(p.price)} each</small><button class="remove" data-remove="${p.id}">Remove</button></div><div class="quantity"><button data-minus="${p.id}" aria-label="Decrease ${p.name} quantity">−</button><span>${cart[p.id]}</span><button data-add="${p.id}" aria-label="Increase ${p.name} quantity">+</button></div><b>${money(p.price*cart[p.id])}</b></div>`).join(''):'<div class="empty"><h3>A little room for discovery.</h3><p>Your bag is empty.</p><button class="primary" data-close="bag">Continue exploring ↗</button></div>';$('#bag-summary').innerHTML=list.length?`<div class="bag-total"><span>Subtotal</span><span>${money(list.reduce((n,p)=>n+p.price*cart[p.id],0))} USD</span></div><p class="catalog-note">This is the preview collection. Checkout is not available yet and no payment will be taken.</p>`:''}
function openBag(){renderBag();$('#bag').showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.category)filter(d.category);if(d.detail)detail(+d.detail);if(d.add)add(+d.add);if(d.close)$('#'+d.close).close();if(d.minus){if(--cart[d.minus]<=0)delete cart[d.minus];save();renderBag()}if(d.remove){delete cart[d.remove];save();renderBag()}});
$('#bag-open').onclick=openBag;$('#footer-bag').onclick=openBag;$('#reset').onclick=()=>{category='All';query='';$('#search').value='';render()};$('#searchform').onsubmit=e=>{e.preventDefault();$('#shop').scrollIntoView({behavior:'smooth'})};$('#search').oninput=e=>{query=e.target.value.trim().toLowerCase();render()};document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));render();save();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'read_rosaino_collection',description:'Read Rosaino concept products and indicative USD prices. These products cannot be ordered yet.',inputSchema:{type:'object',properties:{category:{type:'string',enum:['All',...cats]}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='category')||(input.category!==undefined&&!['All',...cats].includes(input.category)))throw new Error('Choose a valid collection.');return {orderingAvailable:false,products:products.filter(p=>!input.category||input.category==='All'||input.category===p.category).map(({id,name,category,price})=>({id,name,category,price,currency:'USD'}))}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
